[package]
name = "sapling"
version = "0.1.0"
authors = ["mkirsche"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

failure = "*"
seq_io = "0.3.0"
suffix = "*"

